### ISSUE TITLE
(error)/(make-condition) fails to set condition slots

### ISSUE THREAD

**Issue by piknik** [Shinmera/modularize-interfaces#1]
Hello,

I'm using radiance wherein I've come across this issue when creating database compatibility code. In my code I require access to the `'db::field` slot in the `'db:invalid-field` condition so I am able to create adapter code for when a database implementation fails to support a field type.

The peculiar issue is apparent with the following code:
```
(handler-case (error 'db:invalid-field :field 'hi)
	   (db:invalid-field (e) (format t "Got ~S~%" (slot-value e 'db::field))))
```
The following error occurs:
```
The slot DATABASE::FIELD is unbound in the object
Condition of type DATABASE:INVALID-FIELD..
```
which is very odd as you can see the field being populated.
The following code presents the same error:
```
(slot-value (make-condition 'db:invalid-field :field 'hi) 'db::field)
```
To keep my sanity, here is code that is expected to work and does work:
```
(define-condition my-condition (error condition)
	   ((field :initarg :field :initform (error "FIELD required."))))
(slot-value (make-condition 'my-condition :field 'hi") 'field)
```
I can only presume that there is something going wrong in the `modularize-interfaces` package.

**Comment by piknik** [comment]
This issue is worked around by re-defining the condition outside of the `define-interface` body:
```
(define-condition db:invalid-field (error db:condition)
    ((db::field :initarg :field :initform (error "FIELD required."))))
```
So then the following code works:
```
(handler-case (error 'db:invalid-field :field 'hi)
	   (db:invalid-field (e) (format t "Got ~S~%" (slot-value e 'db::field))))
```
```
Got HI
NIL
```

**Comment by Shinmera** [comment]
Wow, can't believe that went unnoticed for so long. Thanks a lot, and sorry for the undoubtedly very confusing debugging session. The latest patch should fix the emission of the condition definition form.

I'm also interested to hear a bit more about your use case for radiance, as it sounds quite interesting, if you are willing to share a bit about it?

**Comment by piknik** [comment]
@Shinmera 
Thank you for the prompt response and fix! It's very much appreciated.

Radiance is being used as a fundamental component of an ERP software I'm building out for a transportation company. The architecture of radiance is very desirable and appears to have many design decisions towards scalability. I'm grateful that you've developed this and many other pieces of software which saves a lot of time! I'll return the favor somehow.

**Comment by Shinmera** [comment]
That's really exciting! I don't know how much you can say publicly of course, but reading an article about it would be really cool!
